apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: gloo
    gloo: ingress-proxy
  name: ingress-proxy
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.deployment.ingressProxy.replicas }}
  selector:
    matchLabels:
      gloo: ingress-proxy
  template:
    metadata:
      labels:
        gloo: ingress-proxy
    spec:
      containers:
      - args: ["--disable-hot-restart"]
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: {{ .Values.deployment.ingressProxy.image }}
        imagePullPolicy: {{ .Values.deployment.imagePullPolicy }}
        name: ingress-proxy
        ports:
        - containerPort: {{ .Values.deployment.ingressProxy.httpPort }}
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/envoy
          name: envoy-config
      volumes:
      - configMap:
          name: ingress-envoy-config
        name: envoy-config